


knitr::opts_chunk$set(echo = TRUE)

#  Explore global development with R
# Today, you will load a filtered gapminder dataset -  with a subset of data on global development from 1952 - 2007 in increments of 5 years - to capture the period between the Second World War and the Global Financial Crisis. 
# Your task: Explore the data and visualise it in both static and animated ways, providing answers and solutions to 7 questions/tasks below.**
  
  ## Get the necessary packages

install.packages("gganimate")
install.packages("gifski")
install.packages("av")
install.packages("gapminder")

install.packages("rmarkdown")

library(tidyverse)
library(gganimate)
library(gifski)
library(av)
library(gapminder)

# Look at the data and tackle the tasks
# First, see which specific years are actually represented in the dataset and what variables are being recorded for each country. Note that when you run the cell below, Rmarkdown will give you two results - one for each line - that you can flip between.

str(gapminder)
unique(gapminder$year)
head(gapminder)


# The dataset contains information on each country in the sampled year, its continent, life expectancy, population, and GDP per capita.

# Let's plot all the countries in 1952.
theme_set(theme_bw())  # set theme to white background for better visibility
ggplot(subset(gapminder, year == 1952), aes(gdpPercap, lifeExp, size = pop)) +
  geom_point() +
  scale_x_log10() 


# We see an interesting spread with an outlier to the right. Answer the following questions, please:

# 1. Why does it make sense to have a log10 scale on x axis?
# Besause one data point has as value above 9000 GDP per capita. which makes the scale go crazy

gapminder %>% 
  filter(gdpPercap > 90000) %>% 
  filter(year == 1952)

# 2. Who is the outlier (the richest country in 1952 - far right on x axis)?* 
# The outlier is Kuwait in Asia with a pdpPercap on 108382

# Next, you can generate a similar plot for 2007 and compare the differences

ggplot(subset(gapminder, year == 2007), aes(gdpPercap, lifeExp, size = pop)) +
  geom_point() +
  scale_x_log10() 

# The black bubbles are a bit hard to read, the comparison would be easier with a bit more visual differentiation.
# Tasks:
  # 3. Differentiate the **continents** by color, and fix the axis labels and units to be more legible (**Hint**: the 2.50e+08 is so called "scientific notation", which you might want to eliminate)*

ggplot(subset(gapminder, year == 2007), aes(gdpPercap, lifeExp, size = pop)) +
  geom_point() +
  scale_x_log10() +
  geom_jitter(alpha = 0.5, aes(color = country))

  # 4. *What are the five richest countries in the world in 2007?*

gapminder %>% 
  filter(year == 2007) %>% 
  arrange(desc(gdpPercap)) %>% 
  head(5)

# Norway, Kuwait, Singapore, United States and Ireland 

##  Make it move!

# The comparison would be easier if we had the two graphs together, animated. We have a lovely tool in R to do this: the `gganimate` package. Beware that there may be other packages your operating system needs in order to glue interim images into an animation or video. Read the messages when installing the package.

# Also, there are *two* ways of animating the gapminder ggplot.

### Option 1: Animate using transition_states() 

# The first step is to create the object-to-be-animated
# r anim1 start

anim <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop)) +
  geom_point() +
  scale_x_log10()  # convert x to log scale
anim

# This plot collates all the points across time. The next step is to split it into years and animate it. This may take some time, depending on the processing power of your computer (and other things you are asking it to do). Beware that the animation might appear in the bottom right 'Viewer' pane, not in this rmd preview. You need to `knit` the document to get the visual inside an html file.

anim + transition_states(year, 
                         transition_length = 1,
                         state_length = 1)

# 5. Can you add a title to one or both of the animations above that will change* 
  # in sync with the animation?* *(**Hint**: search labeling for `transition_states()` and `transition_time()` functions respectively)*
  
# I added transition_time(20, 1-15)
  
  # 6. *Can you made the axes' labels and units more readable? Consider expanding the abreviated lables as well as the scientific notation in the legend and x axis to whole numbers.*

#To make the axes more readable i used the function 'labs' 
anim2 <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop)) +
  geom_point() +
  scale_x_log10() + # convert x to log scale
  transition_time(year) +
  labs(title = "Year: {frame_time}",
       size = "Population",
       x = "GDP Per Capital",
       y = "Life Expectancy")
anim2


# 7. *Come up with a question you want to answer using the gapminder data and write it down. Then, create a data visualisation that answers the question and explain how your visualization answers the question. (Example: you wish to see what was mean life expectancy across the continents in the year you were born versus your parents' birth years). [Hint: if you wish to have more data than is in the filtered gapminder, you can load either the `gapminder_unfiltered` dataset and download more at https://www.gapminder.org/data/ ]*












